// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type APIStandard struct {
	APIStandardHandle string           `db:"api_standard_handle" json:"api_standard_handle"`
	Description       pgtype.Text      `db:"description" json:"description"`
	KeyMethod         string           `db:"key_method" json:"key_method"`
	KeyField          pgtype.Text      `db:"key_field" json:"key_field"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Embedding struct {
	EmbeddingsID int32                  `db:"embeddings_id" json:"embeddings_id"`
	TextID       pgtype.Text            `db:"text_id" json:"text_id"`
	Owner        string                 `db:"owner" json:"owner"`
	ProjectID    int32                  `db:"project_id" json:"project_id"`
	LLMServiceID int32                  `db:"llm_service_id" json:"llm_service_id"`
	Text         pgtype.Text            `db:"text" json:"text"`
	Vector       pgvector_go.HalfVector `db:"vector" json:"vector"`
	VectorDim    int32                  `db:"vector_dim" json:"vector_dim"`
	Metadata     []byte                 `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamp       `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp       `db:"updated_at" json:"updated_at"`
}

type KeyMethod struct {
	KeyMethod string `db:"key_method" json:"key_method"`
}

type LlmService struct {
	LLMServiceID     int32            `db:"llm_service_id" json:"llm_service_id"`
	LLMServiceHandle string           `db:"llm_service_handle" json:"llm_service_handle"`
	Owner            string           `db:"owner" json:"owner"`
	Endpoint         string           `db:"endpoint" json:"endpoint"`
	Description      pgtype.Text      `db:"description" json:"description"`
	APIKey           pgtype.Text      `db:"api_key" json:"api_key"`
	APIStandard      string           `db:"api_standard" json:"api_standard"`
	Model            string           `db:"model" json:"model"`
	Dimensions       int32            `db:"dimensions" json:"dimensions"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Project struct {
	ProjectID      int32            `db:"project_id" json:"project_id"`
	ProjectHandle  string           `db:"project_handle" json:"project_handle"`
	Owner          string           `db:"owner" json:"owner"`
	Description    pgtype.Text      `db:"description" json:"description"`
	MetadataScheme pgtype.Text      `db:"metadata_scheme" json:"metadata_scheme"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type ProjectsLlmService struct {
	ProjectID    int32            `db:"project_id" json:"project_id"`
	LLMServiceID int32            `db:"llm_service_id" json:"llm_service_id"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type User struct {
	UserHandle string           `db:"user_handle" json:"user_handle"`
	Name       pgtype.Text      `db:"name" json:"name"`
	Email      string           `db:"email" json:"email"`
	VdbAPIKey  string           `db:"vdb_api_key" json:"vdb_api_key"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type UsersLlmService struct {
	UserHandle   string           `db:"user_handle" json:"user_handle"`
	LLMServiceID int32            `db:"llm_service_id" json:"llm_service_id"`
	Role         string           `db:"role" json:"role"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type UsersProject struct {
	UserHandle string           `db:"user_handle" json:"user_handle"`
	ProjectID  int32            `db:"project_id" json:"project_id"`
	Role       string           `db:"role" json:"role"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type VdbRole struct {
	VdbRole string `db:"vdb_role" json:"vdb_role"`
}
